[tool.poetry]
name = "rl-book"
packages = [
    { include = "rl_book" }
]

version = "0.1.0"
description = "…"
authors = ["hermanmichaels <hrmnmichaels@gmail.com>"]

[tool.poetry.dependencies]
python = "3.12.12"
matplotlib = "3.9"
mypy = "1.15"
numpy = "2.1"
black = "22.3.0"
ipdb = "0.13.13"
flake8 = "7.0.0"
isort = "^5.10.1"
pygame = "2.6.0"
torch = "2.3.1"
pytest = "8.3.5"
pettingzoo = "1.25.0"
gymnasium = "1.2.3"

